export const FIELD_NOTES_QUESTIONS = [
  "What is Field Notes?",
  "What is a monolithic CMS?",
  "Why is a monolithic CMS considered a strategic risk?",
  "What is composable architecture in content management?",
  "What is the difference between monolithic and headless CMS?",
  "What is Optimizely Graph?",
  "What is the Content JS SDK?",
  "What is Visual Builder in Optimizely?",
  "What is atomic content?",
  "How does a headless CMS improve page load time?",
  "What is Opal?",
  "How does Optimizely route prompts in Opal?",
  "What is Mycroft?",
  "What is the difference between Fast mode, Enriched mode, and Auto mode in Opal?",
  "How can I reduce AI inference costs at scale?",
  "What is Answer Engine Optimization?",
  "What are the benefits of a B2B ecommerce website?",
  "How can B2B ecommerce improve self-service?",
  "What role does PIM play in B2B ecommerce?",
  "What percentage of B2B buyers research online before buying?",
  "How does Optimizely approach personalization?",
  "What is conversion rate optimization?",
  "What are the top Mixpanel alternatives for enterprise product analytics?",
  "Why do Shopify and BigCommerce fall short for complex B2B needs?",
  "Why is CMS architecture now a board-level decision?",
  "How do you build a business case for a CMS migration?",
  "How do you align engineering and marketing teams on CMS decisions?",
  "How do you avoid a big bang platform migration?",
  "What is semantic debt?",
  "How should I structure content for AI assistants and generative search?",
  "What upcoming Optimizely webinars can I register for?",
  "Find recent Field Notes articles about AI.",
  "What are the upcoming events?",
];
